//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> ChildID { get; set; }
        public Nullable<int> GrandChildID { get; set; }
        public Nullable<double> ChildUsageQty { get; set; }
        public string ChildUsageUnit { get; set; }
        public Nullable<double> GrandChildUsageQty { get; set; }
        public string GrandChildUsageUnit { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual PART PART { get; set; }
        public virtual PART PART1 { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
