//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM
    {
        public int ID { get; set; }
        public double ChildUsageQty { get; set; }
        public string ChildUsageUnit { get; set; }
        public Nullable<double> GrandChildUsageQty { get; set; }
        public string GrandChildUsageUnit { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string ParentPNo { get; set; }
        public string ChildPNo { get; set; }
        public string GrandChildPNo { get; set; }
        public bool IsParentProduct { get; set; }
        public bool IsParentPart { get; set; }
    }
}
