//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOM()
        {
            this.BOMS_AND_NORMS = new HashSet<BOMS_AND_NORMS>();
        }
    
        public int ID { get; set; }
        public double Consumption { get; set; }
        public string ConsumptionUnit { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ParentPNo { get; set; }
        public string ChildPNo { get; set; }
        public Nullable<bool> IsParentProduct { get; set; }
        public double WasteAmount { get; set; }
        public double TotalConsumption { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> ProcessID { get; set; }
    
        public virtual PRODUCTIONPROCESS PRODUCTIONPROCESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOMS_AND_NORMS> BOMS_AND_NORMS { get; set; }
    }
}
