//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMS_AND_NORMS
    {
        public Nullable<int> BOMID { get; set; }
        public Nullable<int> NormID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime IssuedDT { get; set; }
    
        public virtual BOM BOM { get; set; }
    }
}
