//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_PLANS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAR_PLANS()
        {
            this.CAR_PLANS1 = new HashSet<CAR_PLANS>();
        }
    
        public int ID { get; set; }
        public int CarID { get; set; }
        public double Amount { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime DueDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAR_PLANS> CAR_PLANS1 { get; set; }
        public virtual CAR_PLANS CAR_PLANS2 { get; set; }
    }
}
