//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COOKIES_CONFIRMATION
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime IssuedDT { get; set; }
        public string MacAdress { get; set; }
        public bool Confirmation { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
