//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTHSNEntities : DbContext
    {
        public DBTHSNEntities()
            : base("name=DBTHSNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOM> BOMS { get; set; }
        public virtual DbSet<COMPANy> COMPANIES { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERS { get; set; }
        public virtual DbSet<PART1738DOCS> PART1738DOCS { get; set; }
        public virtual DbSet<PARTIMAGE> PARTIMAGES { get; set; }
        public virtual DbSet<PARTPACK> PARTPACKS { get; set; }
        public virtual DbSet<PART> PARTS { get; set; }
        public virtual DbSet<PCONTRACT> PCONTRACTS { get; set; }
        public virtual DbSet<PERMISSION> PERMISSIONS { get; set; }
        public virtual DbSet<PRODUCT1738DOCS> PRODUCT1738DOCS { get; set; }
        public virtual DbSet<PRODUCTIMAGE> PRODUCTIMAGES { get; set; }
        public virtual DbSet<PRODUCTPACK> PRODUCTPACKS { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTS { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
        public virtual DbSet<SCONTRACT> SCONTRACTS { get; set; }
        public virtual DbSet<SPL> SPLs { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIERS { get; set; }
        public virtual DbSet<USER_ENTRIES> USER_ENTRIES { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
