//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBTHSNEntities : DbContext
    {
        public DBTHSNEntities()
            : base("name=DBTHSNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOM> BOMS { get; set; }
        public virtual DbSet<COMPANy> COMPANIES { get; set; }
        public virtual DbSet<COMPANY_LICENSES> COMPANY_LICENSES { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERS { get; set; }
        public virtual DbSet<F_CONTRACTS> F_CONTRACTS { get; set; }
        public virtual DbSet<F_TRANSPORT_TYPES> F_TRANSPORT_TYPES { get; set; }
        public virtual DbSet<F_WAYBILL_DOCS> F_WAYBILL_DOCS { get; set; }
        public virtual DbSet<F_WAYBILLS> F_WAYBILLS { get; set; }
        public virtual DbSet<FORWARDER> FORWARDERS { get; set; }
        public virtual DbSet<P_CONTRACT_DOCS> P_CONTRACT_DOCS { get; set; }
        public virtual DbSet<P_CONTRACT_PARTS> P_CONTRACT_PARTS { get; set; }
        public virtual DbSet<P_CONTRACTS> P_CONTRACTS { get; set; }
        public virtual DbSet<P_INVOICE_DOCS> P_INVOICE_DOCS { get; set; }
        public virtual DbSet<P_INVOICE_PACKINGLISTS> P_INVOICE_PACKINGLISTS { get; set; }
        public virtual DbSet<P_INVOICE_PARTS> P_INVOICE_PARTS { get; set; }
        public virtual DbSet<P_INVOICES> P_INVOICES { get; set; }
        public virtual DbSet<P_ORDER_DOCS> P_ORDER_DOCS { get; set; }
        public virtual DbSet<P_ORDER_PARTS> P_ORDER_PARTS { get; set; }
        public virtual DbSet<P_ORDERS> P_ORDERS { get; set; }
        public virtual DbSet<P_PACKINGLIST_DOCS> P_PACKINGLIST_DOCS { get; set; }
        public virtual DbSet<P_WRHS_EXPENSE_DOCS> P_WRHS_EXPENSE_DOCS { get; set; }
        public virtual DbSet<P_WRHS_EXPENSES> P_WRHS_EXPENSES { get; set; }
        public virtual DbSet<P_WRHS_INCOME_DOCS> P_WRHS_INCOME_DOCS { get; set; }
        public virtual DbSet<P_WRHS_INCOMES> P_WRHS_INCOMES { get; set; }
        public virtual DbSet<PART_WRHS> PART_WRHS { get; set; }
        public virtual DbSet<PART1738DOCS> PART1738DOCS { get; set; }
        public virtual DbSet<PARTIMAGE> PARTIMAGES { get; set; }
        public virtual DbSet<PARTPACK> PARTPACKS { get; set; }
        public virtual DbSet<PARTPLAN> PARTPLANS { get; set; }
        public virtual DbSet<PART> PARTS { get; set; }
        public virtual DbSet<PERMISSIONMODULE> PERMISSIONMODULES { get; set; }
        public virtual DbSet<PERMISSION> PERMISSIONS { get; set; }
        public virtual DbSet<PROD_SHOPS> PROD_SHOPS { get; set; }
        public virtual DbSet<PRODUCT1738DOCS> PRODUCT1738DOCS { get; set; }
        public virtual DbSet<PRODUCTIMAGE> PRODUCTIMAGES { get; set; }
        public virtual DbSet<PRODUCTPACK> PRODUCTPACKS { get; set; }
        public virtual DbSet<PRODUCTPLAN> PRODUCTPLANS { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTS { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
        public virtual DbSet<S_CONTRACTS> S_CONTRACTS { get; set; }
        public virtual DbSet<SAMPLE_FILES> SAMPLE_FILES { get; set; }
        public virtual DbSet<SPL> SPLs { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIERS { get; set; }
        public virtual DbSet<USER_ENTRIES> USER_ENTRIES { get; set; }
        public virtual DbSet<USER_LICENSES> USER_LICENSES { get; set; }
        public virtual DbSet<USERIMAGE> USERIMAGES { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    
        public virtual ObjectResult<GetPartsInfo_Result> GetPartsInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPartsInfo_Result>("GetPartsInfo");
        }
    
        public virtual ObjectResult<GetPartsInfo_by_supplierID_Result> GetPartsInfo_by_supplierID(Nullable<int> supplierID)
        {
            var supplierIDParameter = supplierID.HasValue ?
                new ObjectParameter("SupplierID", supplierID) :
                new ObjectParameter("SupplierID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPartsInfo_by_supplierID_Result>("GetPartsInfo_by_supplierID", supplierIDParameter);
        }
    
        public virtual ObjectResult<GetPartsInfo_by_type_Result> GetPartsInfo_by_type(string type)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPartsInfo_by_type_Result>("GetPartsInfo_by_type", typeParameter);
        }
    
        public virtual ObjectResult<GetPartsInfo_by_type_and_supplierID_Result> GetPartsInfo_by_type_and_supplierID(string type, Nullable<int> supplierID)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var supplierIDParameter = supplierID.HasValue ?
                new ObjectParameter("SupplierID", supplierID) :
                new ObjectParameter("SupplierID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPartsInfo_by_type_and_supplierID_Result>("GetPartsInfo_by_type_and_supplierID", typeParameter, supplierIDParameter);
        }
    
        public virtual ObjectResult<GetSupplierParts_Result> GetSupplierParts(Nullable<int> supplierID)
        {
            var supplierIDParameter = supplierID.HasValue ?
                new ObjectParameter("SupplierID", supplierID) :
                new ObjectParameter("SupplierID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSupplierParts_Result>("GetSupplierParts", supplierIDParameter);
        }
    }
}
