//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTHSNEntities : DbContext
    {
        public DBTHSNEntities()
            : base("name=DBTHSNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOMS> BOMS { get; set; }
        public virtual DbSet<COMPANIES> COMPANIES { get; set; }
        public virtual DbSet<COMPANY_LICENSES> COMPANY_LICENSES { get; set; }
        public virtual DbSet<CUSTOMERS> CUSTOMERS { get; set; }
        public virtual DbSet<F_CONTRACTS> F_CONTRACTS { get; set; }
        public virtual DbSet<F_TRANSPORT_TYPES> F_TRANSPORT_TYPES { get; set; }
        public virtual DbSet<F_WAYBILL_DOCS> F_WAYBILL_DOCS { get; set; }
        public virtual DbSet<F_WAYBILLS> F_WAYBILLS { get; set; }
        public virtual DbSet<FORWARDERS> FORWARDERS { get; set; }
        public virtual DbSet<P_CONTRACT_DOCS> P_CONTRACT_DOCS { get; set; }
        public virtual DbSet<P_CONTRACTS> P_CONTRACTS { get; set; }
        public virtual DbSet<P_INVOICE_DOCS> P_INVOICE_DOCS { get; set; }
        public virtual DbSet<P_INVOICE_PACKINGLISTS> P_INVOICE_PACKINGLISTS { get; set; }
        public virtual DbSet<P_INVOICES> P_INVOICES { get; set; }
        public virtual DbSet<P_ORDER_DOCS> P_ORDER_DOCS { get; set; }
        public virtual DbSet<P_ORDERS> P_ORDERS { get; set; }
        public virtual DbSet<P_PACKINGLIST_DOCS> P_PACKINGLIST_DOCS { get; set; }
        public virtual DbSet<P_WRHS_EXPENSES> P_WRHS_EXPENSES { get; set; }
        public virtual DbSet<P_WRHS_INCOME_DOCS> P_WRHS_INCOME_DOCS { get; set; }
        public virtual DbSet<P_WRHS_INCOMES> P_WRHS_INCOMES { get; set; }
        public virtual DbSet<PART_WRHS> PART_WRHS { get; set; }
        public virtual DbSet<PART1738DOCS> PART1738DOCS { get; set; }
        public virtual DbSet<PARTIMAGES> PARTIMAGES { get; set; }
        public virtual DbSet<PARTPACKS> PARTPACKS { get; set; }
        public virtual DbSet<PARTPLANS> PARTPLANS { get; set; }
        public virtual DbSet<PARTS> PARTS { get; set; }
        public virtual DbSet<PERMISSIONS> PERMISSIONS { get; set; }
        public virtual DbSet<PROD_SHOPS> PROD_SHOPS { get; set; }
        public virtual DbSet<PRODUCT1738DOCS> PRODUCT1738DOCS { get; set; }
        public virtual DbSet<PRODUCTIMAGES> PRODUCTIMAGES { get; set; }
        public virtual DbSet<PRODUCTPACKS> PRODUCTPACKS { get; set; }
        public virtual DbSet<PRODUCTPLANS> PRODUCTPLANS { get; set; }
        public virtual DbSet<PRODUCTS> PRODUCTS { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<S_CONTRACTS> S_CONTRACTS { get; set; }
        public virtual DbSet<SPL> SPL { get; set; }
        public virtual DbSet<SUPPLIERS> SUPPLIERS { get; set; }
        public virtual DbSet<USER_ENTRIES> USER_ENTRIES { get; set; }
        public virtual DbSet<USER_LICENSES> USER_LICENSES { get; set; }
        public virtual DbSet<USERIMAGES> USERIMAGES { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<PERMISSIONMODULE> PERMISSIONMODULES { get; set; }
    }
}
