//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_TRANSPORT_TYPES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public F_TRANSPORT_TYPES()
        {
            this.F_WAYBILLS = new HashSet<F_WAYBILLS>();
        }
    
        public int ID { get; set; }
        public string TransportType { get; set; }
        public Nullable<double> ExtLgth { get; set; }
        public Nullable<double> ExtWdth { get; set; }
        public Nullable<double> ExtHght { get; set; }
        public Nullable<double> IntLgth { get; set; }
        public Nullable<double> IntWdth { get; set; }
        public Nullable<double> IntHght { get; set; }
        public string Unit { get; set; }
        public Nullable<double> CapableOfLifting { get; set; }
        public Nullable<double> TransportWeight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<F_WAYBILLS> F_WAYBILLS { get; set; }
    }
}
