//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_TRANSPORT_TYPES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public F_TRANSPORT_TYPES()
        {
            this.F_WAYBILLS = new HashSet<F_WAYBILLS>();
            this.P_INVOICE_PACKINGLISTS = new HashSet<P_INVOICE_PACKINGLISTS>();
        }
    
        public int ID { get; set; }
        public string TransportType { get; set; }
        public double ExtLgth { get; set; }
        public double ExtWdth { get; set; }
        public double ExtHght { get; set; }
        public double IntLgth { get; set; }
        public double IntWdth { get; set; }
        public double IntHght { get; set; }
        public Nullable<double> CapableOfLifting { get; set; }
        public Nullable<double> TransportWeight { get; set; }
        public int UnitID { get; set; }
    
        public virtual UNIT UNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<F_WAYBILLS> F_WAYBILLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_INVOICE_PACKINGLISTS> P_INVOICE_PACKINGLISTS { get; set; }
    }
}
