//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialRequirement
    {
        public string ProductNo { get; set; }
        public string PartNo { get; set; }
        public Nullable<double> TotalConsumption { get; set; }
    }
}
