//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_INVOICE_PACKINGLISTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_INVOICE_PACKINGLISTS()
        {
            this.F_WAYBILLS = new HashSet<F_WAYBILLS>();
            this.P_PACKINGLIST_DOCS = new HashSet<P_PACKINGLIST_DOCS>();
        }
    
        public int ID { get; set; }
        public int InvoiceID { get; set; }
        public string PackingListNo { get; set; }
        public int PartID { get; set; }
        public Nullable<double> PrLength { get; set; }
        public Nullable<double> PrWidth { get; set; }
        public Nullable<double> PrHeight { get; set; }
        public Nullable<double> PrCBM { get; set; }
        public Nullable<double> PrGrWeight { get; set; }
        public string PrPackMaterial { get; set; }
        public string ScPackMaterial { get; set; }
        public Nullable<double> ScLength { get; set; }
        public Nullable<double> ScWidth { get; set; }
        public Nullable<double> ScHeight { get; set; }
        public Nullable<double> ScCBM { get; set; }
        public Nullable<double> ScGrWeight { get; set; }
        public string PltType { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<F_WAYBILLS> F_WAYBILLS { get; set; }
        public virtual P_INVOICES P_INVOICES { get; set; }
        public virtual PART PART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_PACKINGLIST_DOCS> P_PACKINGLIST_DOCS { get; set; }
    }
}
