//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_INVOICE_PACKINGLISTS
    {
        public int ID { get; set; }
        public int InvoiceID { get; set; }
        public string PackingListNo { get; set; }
        public int TransportTypeID { get; set; }
        public string TransportNo { get; set; }
        public int PartID { get; set; }
        public Nullable<double> PieceWeight { get; set; }
        public Nullable<double> PrLength { get; set; }
        public Nullable<double> PrWidth { get; set; }
        public Nullable<double> PrHeight { get; set; }
        public Nullable<double> PrCBM { get; set; }
        public Nullable<double> PrAmount { get; set; }
        public Nullable<double> PrNetWeight { get; set; }
        public Nullable<double> PrGrWeight { get; set; }
        public string PrPackMaterial { get; set; }
        public string ScPackMaterial { get; set; }
        public Nullable<double> ScLength { get; set; }
        public Nullable<double> ScWidth { get; set; }
        public Nullable<double> ScHeight { get; set; }
        public Nullable<double> ScCBM { get; set; }
        public Nullable<double> NoOfBoxes { get; set; }
        public Nullable<double> SchedPack { get; set; }
        public Nullable<double> ScNetWeight { get; set; }
        public Nullable<double> ScGrWeight { get; set; }
        public string PalletType { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual F_TRANSPORT_TYPES F_TRANSPORT_TYPES { get; set; }
        public virtual P_INVOICES P_INVOICES { get; set; }
        public virtual PART PART { get; set; }
    }
}
