//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_INVOICE_PACKINGLISTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_INVOICE_PACKINGLISTS()
        {
            this.TRACINGS = new HashSet<TRACING>();
            this.P_PACKINGLIST_PARTS = new HashSet<P_PACKINGLIST_PARTS>();
        }
    
        public int ID { get; set; }
        public int InvoiceID { get; set; }
        public int TransportTypeID { get; set; }
        public string TransportNo { get; set; }
        public string PackingListNo { get; set; }
        public string SealNo { get; set; }
        public string Comment { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> InTransit { get; set; }
        public Nullable<double> TotalCBM { get; set; }
        public Nullable<double> TotalGrWeight { get; set; }
        public Nullable<double> TotalNetWeight { get; set; }
    
        public virtual F_TRANSPORT_TYPES F_TRANSPORT_TYPES { get; set; }
        public virtual P_INVOICES P_INVOICES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRACING> TRACINGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_PACKINGLIST_PARTS> P_PACKINGLIST_PARTS { get; set; }
    }
}
