//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_ORDERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_ORDERS()
        {
            this.P_INVOICES = new HashSet<P_INVOICES>();
            this.P_ORDER_DOCS = new HashSet<P_ORDER_DOCS>();
            this.P_ORDER_PARTS = new HashSet<P_ORDER_PARTS>();
        }
    
        public int ID { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public int SupplierID { get; set; }
        public int ContractID { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Currency { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual COMPANy COMPANy { get; set; }
        public virtual P_CONTRACTS P_CONTRACTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_INVOICES> P_INVOICES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_ORDER_DOCS> P_ORDER_DOCS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_ORDER_PARTS> P_ORDER_PARTS { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
