//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_ORDER_PARTS
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> PartID { get; set; }
        public double Price { get; set; }
        public double Amount { get; set; }
        public double TotalPrice { get; set; }
        public Nullable<double> MOQ { get; set; }
        public Nullable<int> UnitID { get; set; }
    
        public virtual P_ORDERS P_ORDERS { get; set; }
        public virtual PART PART { get; set; }
        public virtual UNIT UNIT { get; set; }
    }
}
