//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_PROFORMA_INVOICES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_PROFORMA_INVOICES()
        {
            this.P_PROFORMA_INVOICE_DOCS = new HashSet<P_PROFORMA_INVOICE_DOCS>();
        }
    
        public int ID { get; set; }
        public string PrInvoiceNo { get; set; }
        public int InvoiceID { get; set; }
        public int SupplierID { get; set; }
        public double Amount { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string Currency { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual COMPANy COMPANy { get; set; }
        public virtual P_INVOICES P_INVOICES { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_PROFORMA_INVOICE_DOCS> P_PROFORMA_INVOICE_DOCS { get; set; }
    }
}
