//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_WRHS_EXPENSES
    {
        public int ID { get; set; }
        public string DocNo { get; set; }
        public int PartID { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Unit { get; set; }
        public Nullable<double> PiecePrice { get; set; }
        public string Currency { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<int> RecieverWhID { get; set; }
        public Nullable<int> ShopID { get; set; }
        public int WHID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Description { get; set; }
    
        public virtual PART_WRHS PART_WRHS { get; set; }
        public virtual PARTS PARTS { get; set; }
        public virtual PROD_SHOPS PROD_SHOPS { get; set; }
    }
}
