//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTPLANS_DAILY
    {
        public int ID { get; set; }
        public int PlanID { get; set; }
        public System.DateTime Day { get; set; }
        public double DayShift { get; set; }
        public double NightShift { get; set; }
        public double Total { get; set; }
    
        public virtual PARTPLAN PARTPLAN { get; set; }
    }
}
