//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_WRHS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PART_WRHS()
        {
            this.PART_STOCKS = new HashSet<PART_STOCKS>();
            this.PART_WASTE_WRHS_EXPENSES = new HashSet<PART_WASTE_WRHS_EXPENSES>();
            this.PART_WASTE_WRHS_EXPENSES1 = new HashSet<PART_WASTE_WRHS_EXPENSES>();
            this.PART_WASTE_WRHS_INCOMES = new HashSet<PART_WASTE_WRHS_INCOMES>();
            this.PART_WASTE_WRHS_INCOMES1 = new HashSet<PART_WASTE_WRHS_INCOMES>();
            this.PART_WRHS_EXPENSES = new HashSet<PART_WRHS_EXPENSES>();
            this.PART_WRHS_EXPENSES1 = new HashSet<PART_WRHS_EXPENSES>();
            this.PART_WRHS_INCOMES = new HashSet<PART_WRHS_INCOMES>();
            this.PART_WRHS_INCOMES1 = new HashSet<PART_WRHS_INCOMES>();
            this.WASTE_STOCKS = new HashSet<WASTE_STOCKS>();
        }
    
        public int ID { get; set; }
        public string WHName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> MRP { get; set; }
        public Nullable<int> ShopID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PART_STOCKS> PART_STOCKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PART_WASTE_WRHS_EXPENSES> PART_WASTE_WRHS_EXPENSES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PART_WASTE_WRHS_EXPENSES> PART_WASTE_WRHS_EXPENSES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PART_WASTE_WRHS_INCOMES> PART_WASTE_WRHS_INCOMES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PART_WASTE_WRHS_INCOMES> PART_WASTE_WRHS_INCOMES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PART_WRHS_EXPENSES> PART_WRHS_EXPENSES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PART_WRHS_EXPENSES> PART_WRHS_EXPENSES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PART_WRHS_INCOMES> PART_WRHS_INCOMES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PART_WRHS_INCOMES> PART_WRHS_INCOMES1 { get; set; }
        public virtual PROD_SHOPS PROD_SHOPS { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WASTE_STOCKS> WASTE_STOCKS { get; set; }
    }
}
