//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PART()
        {
            this.BLANKING_NORMS = new HashSet<BLANKING_NORMS>();
            this.BLANKING_NORMS1 = new HashSet<BLANKING_NORMS>();
            this.DAMAGED_PARTS = new HashSet<DAMAGED_PARTS>();
            this.P_CONTRACT_PARTS = new HashSet<P_CONTRACT_PARTS>();
            this.P_INVOICE_PARTS = new HashSet<P_INVOICE_PARTS>();
            this.P_ORDER_PARTS = new HashSet<P_ORDER_PARTS>();
            this.P_PACKINGLIST_PARTS = new HashSet<P_PACKINGLIST_PARTS>();
            this.PART_PRODUCTION = new HashSet<PART_PRODUCTION>();
            this.PART_STOCKS = new HashSet<PART_STOCKS>();
            this.PART_WRHS_EXPENSE_PARTS = new HashSet<PART_WRHS_EXPENSE_PARTS>();
            this.PART_WRHS_INCOME_PARTS = new HashSet<PART_WRHS_INCOME_PARTS>();
            this.PARTIMAGES = new HashSet<PARTIMAGE>();
            this.PARTPACKS = new HashSet<PARTPACK>();
            this.PARTPLANS = new HashSet<PARTPLAN>();
            this.SLITTING_NORMS = new HashSet<SLITTING_NORMS>();
            this.SLITTING_NORMS1 = new HashSet<SLITTING_NORMS>();
            this.STAMPING_NORMS = new HashSet<STAMPING_NORMS>();
            this.STAMPING_NORMS1 = new HashSet<STAMPING_NORMS>();
        }
    
        public int ID { get; set; }
        public string PNo { get; set; }
        public string PName { get; set; }
        public double PWeight { get; set; }
        public double PLength { get; set; }
        public double PWidth { get; set; }
        public double PHeight { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public int PackID { get; set; }
        public int ShopID { get; set; }
        public bool IsInHouse { get; set; }
        public string Marka { get; set; }
        public string Standart { get; set; }
        public string Coating { get; set; }
        public string Grade { get; set; }
        public double Gauge { get; set; }
        public double Thickness { get; set; }
        public double Pitch { get; set; }
        public int HSCodeID { get; set; }
        public int UnitID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLANKING_NORMS> BLANKING_NORMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLANKING_NORMS> BLANKING_NORMS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAMAGED_PARTS> DAMAGED_PARTS { get; set; }
        public virtual HSCODE HSCODE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_CONTRACT_PARTS> P_CONTRACT_PARTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_INVOICE_PARTS> P_INVOICE_PARTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_ORDER_PARTS> P_ORDER_PARTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_PACKINGLIST_PARTS> P_PACKINGLIST_PARTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PART_PRODUCTION> PART_PRODUCTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PART_STOCKS> PART_STOCKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PART_WRHS_EXPENSE_PARTS> PART_WRHS_EXPENSE_PARTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PART_WRHS_INCOME_PARTS> PART_WRHS_INCOME_PARTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIMAGE> PARTIMAGES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTPACK> PARTPACKS { get; set; }
        public virtual PARTPACK PARTPACK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTPLAN> PARTPLANS { get; set; }
        public virtual SHOP SHOP { get; set; }
        public virtual UNIT UNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SLITTING_NORMS> SLITTING_NORMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SLITTING_NORMS> SLITTING_NORMS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAMPING_NORMS> STAMPING_NORMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAMPING_NORMS> STAMPING_NORMS1 { get; set; }
    }
}
