//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARTS()
        {
            this.P_CONTRACTS = new HashSet<P_CONTRACTS>();
            this.P_INVOICE_PACKINGLISTS = new HashSet<P_INVOICE_PACKINGLISTS>();
            this.P_INVOICES = new HashSet<P_INVOICES>();
            this.P_ORDERS = new HashSet<P_ORDERS>();
            this.P_WRHS_EXPENSES = new HashSet<P_WRHS_EXPENSES>();
            this.P_WRHS_INCOMES = new HashSet<P_WRHS_INCOMES>();
            this.PARTIMAGES = new HashSet<PARTIMAGES>();
            this.PARTPACKS = new HashSet<PARTPACKS>();
            this.PARTPLANS = new HashSet<PARTPLANS>();
        }
    
        public int ID { get; set; }
        public string PNo { get; set; }
        public string PName { get; set; }
        public Nullable<double> PWeight { get; set; }
        public Nullable<double> PLength { get; set; }
        public Nullable<double> PWidth { get; set; }
        public Nullable<double> PHeight { get; set; }
        public string Unit { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string PNo2 { get; set; }
        public string PNo3 { get; set; }
        public string PNo4 { get; set; }
        public Nullable<int> PackID { get; set; }
        public Nullable<bool> IsInhouse { get; set; }
        public Nullable<int> ShopID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_CONTRACTS> P_CONTRACTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_INVOICE_PACKINGLISTS> P_INVOICE_PACKINGLISTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_INVOICES> P_INVOICES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_ORDERS> P_ORDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_WRHS_EXPENSES> P_WRHS_EXPENSES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_WRHS_INCOMES> P_WRHS_INCOMES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIMAGES> PARTIMAGES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTPACKS> PARTPACKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTPLANS> PARTPLANS { get; set; }
    }
}
