//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_WRHS_INCOME_DOCS
    {
        public int ID { get; set; }
        public int IncomeID { get; set; }
        public byte[] Doc { get; set; }
    
        public virtual PART_WRHS_INCOMES PART_WRHS_INCOMES { get; set; }
    }
}
