//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTPLAN
    {
        public int ID { get; set; }
        public Nullable<int> PartID { get; set; }
        public Nullable<double> PlannedQty { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Label { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual PART PART { get; set; }
    }
}
