//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_WASTE_WRHS_INCOME_WASTES
    {
        public int ID { get; set; }
        public int IncomeID { get; set; }
        public int WasteID { get; set; }
        public double Amount { get; set; }
        public Nullable<double> PiecePrice { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public string Comment { get; set; }
        public int UnitID { get; set; }
    
        public virtual PART_WASTE_WRHS_INCOMES PART_WASTE_WRHS_INCOMES { get; set; }
        public virtual UNIT UNIT { get; set; }
        public virtual WASTE WASTE { get; set; }
    }
}
