//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PART()
        {
            this.BOMS = new HashSet<BOM>();
            this.BOMS1 = new HashSet<BOM>();
            this.PARTIMAGES = new HashSet<PARTIMAGE>();
            this.PARTPACKS = new HashSet<PARTPACK>();
            this.PCONTRACTS = new HashSet<PCONTRACT>();
        }
    
        public int ID { get; set; }
        public string PNo { get; set; }
        public string PName { get; set; }
        public Nullable<double> PWeight { get; set; }
        public Nullable<double> PLength { get; set; }
        public Nullable<double> PWidth { get; set; }
        public Nullable<double> PHeight { get; set; }
        public string Unit { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string PNo2 { get; set; }
        public string PNo3 { get; set; }
        public string PNo4 { get; set; }
        public Nullable<int> PackID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOM> BOMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOM> BOMS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIMAGE> PARTIMAGES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTPACK> PARTPACKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCONTRACT> PCONTRACTS { get; set; }
    }
}
