//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTPACK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARTPACK()
        {
            this.PART1738DOCS = new HashSet<PART1738DOCS>();
            this.PARTS = new HashSet<PART>();
        }
    
        public int ID { get; set; }
        public int PartID { get; set; }
        public string PrPackMaterial { get; set; }
        public string Securement { get; set; }
        public string Dunnage { get; set; }
        public double PrLength { get; set; }
        public double PrWidth { get; set; }
        public double PrHeight { get; set; }
        public double PrWeight { get; set; }
        public double PrPackQty { get; set; }
        public string ScPackMaterial { get; set; }
        public double ScLength { get; set; }
        public double ScWidth { get; set; }
        public double ScHeight { get; set; }
        public double ScWeight { get; set; }
        public string PalletType { get; set; }
        public double PltLength { get; set; }
        public double PltWidth { get; set; }
        public double PltHeight { get; set; }
        public double PltWeight { get; set; }
        public double ScPackQty { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PART1738DOCS> PART1738DOCS { get; set; }
        public virtual PART PART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PART> PARTS { get; set; }
    }
}
