//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART1738DOCS
    {
        public int ID { get; set; }
        public int PackID { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> UntilDate { get; set; }
        public Nullable<int> ApproverUserID { get; set; }
        public string Comments { get; set; }
        public byte[] C1738 { get; set; }
        public Nullable<int> UploadedByUserID { get; set; }
    
        public virtual PARTPACK PARTPACK { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
