//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTIMAGES
    {
        public int ID { get; set; }
        public int PartID { get; set; }
        public byte[] Image { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual PARTS PARTS { get; set; }
    }
}
