//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCONTRACT
    {
        public int ID { get; set; }
        public string ContractNo { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public int CompanyID { get; set; }
        public int SupplierID { get; set; }
        public int PartID { get; set; }
        public Nullable<double> Price { get; set; }
        public string Currency { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Incoterms { get; set; }
        public string PaymentTerms { get; set; }
        public Nullable<double> MOQ { get; set; }
        public Nullable<double> MaximumCapacity { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual COMPANy COMPANy { get; set; }
        public virtual PART PART { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
