//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    
    public partial class PERMISSION
    {
        public int ID { get; set; }
        public bool ViewPermit { get; set; }
        public bool ChangePermit { get; set; }
        public int RoleID { get; set; }
        public int PermissionModuleID { get; set; }
        public virtual PERMISSIONMODULE PERMISSIONMODULE { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
