//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISSION
    {
        public int ID { get; set; }
        public string Model { get; set; }
        public Nullable<bool> ViewPermit { get; set; }
        public Nullable<bool> ChangePermit { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ROLE ROLE { get; set; }
    }
}
