//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_WRHS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROD_WRHS()
        {
            this.PROD_STOCKS = new HashSet<PROD_STOCKS>();
            this.PROD_WRHS_EXPENSES = new HashSet<PROD_WRHS_EXPENSES>();
            this.PROD_WRHS_EXPENSES1 = new HashSet<PROD_WRHS_EXPENSES>();
            this.PROD_WRHS_INCOMES = new HashSet<PROD_WRHS_INCOMES>();
            this.PROD_WRHS_INCOMES1 = new HashSet<PROD_WRHS_INCOMES>();
        }
    
        public int ID { get; set; }
        public string WHName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> MRP { get; set; }
        public int ShopID { get; set; }
        public Nullable<int> Account { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_STOCKS> PROD_STOCKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_WRHS_EXPENSES> PROD_WRHS_EXPENSES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_WRHS_EXPENSES> PROD_WRHS_EXPENSES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_WRHS_INCOMES> PROD_WRHS_INCOMES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_WRHS_INCOMES> PROD_WRHS_INCOMES1 { get; set; }
        public virtual SHOP SHOP { get; set; }
        public virtual USER USER { get; set; }
    }
}
