//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_SHOPS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROD_SHOPS()
        {
            this.P_WRHS_EXPENSES = new HashSet<P_WRHS_EXPENSES>();
            this.P_WRHS_INCOMES = new HashSet<P_WRHS_INCOMES>();
            this.PARTS = new HashSet<PART>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string ShopName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual COMPANy COMPANy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_WRHS_EXPENSES> P_WRHS_EXPENSES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_WRHS_INCOMES> P_WRHS_INCOMES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PART> PARTS { get; set; }
    }
}
