//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_WRHS_EXPENSE_PRODUCTS
    {
        public int ID { get; set; }
        public int ExpenseID { get; set; }
        public int ProductID { get; set; }
        public double Amount { get; set; }
        public double PiecePrice { get; set; }
        public double TotalPrice { get; set; }
        public string Comment { get; set; }
        public int UnitID { get; set; }
    
        public virtual PROD_WRHS_EXPENSES PROD_WRHS_EXPENSES { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual UNIT UNIT { get; set; }
    }
}
