//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTPLAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTPLAN()
        {
            this.PRODUCTPLANS_DAILY = new HashSet<PRODUCTPLANS_DAILY>();
        }
    
        public int ID { get; set; }
        public int ProductID { get; set; }
        public double Amount { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime DueDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTPLANS_DAILY> PRODUCTPLANS_DAILY { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
