//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASING_CONTRACT_ITEMS
    {
        public int ID { get; set; }
        public int ContractID { get; set; }
        public int ItemID { get; set; }
        public double Price { get; set; }
        public double Amount { get; set; }
        public double TotalPrice { get; set; }
        public Nullable<double> MOQ { get; set; }
        public Nullable<bool> ActivePart { get; set; }
        public Nullable<int> UnitID { get; set; }
    
        public virtual PURCHASING_CONTRACTS PURCHASING_CONTRACTS { get; set; }
        public virtual PURCHASING_ITEMS PURCHASING_ITEMS { get; set; }
        public virtual UNIT UNIT { get; set; }
    }
}
