//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CONTRACT_PRODUCTS
    {
        public int ID { get; set; }
        public int ContractID { get; set; }
        public int ProductID { get; set; }
        public double PiecePrice { get; set; }
        public double Amount { get; set; }
        public int UnitID { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual S_CONTRACTS S_CONTRACTS { get; set; }
        public virtual UNIT UNIT { get; set; }
    }
}
