//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_ORDERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public S_ORDERS()
        {
            this.S_ORDER_PRODUCTS = new HashSet<S_ORDER_PRODUCTS>();
        }
    
        public int ID { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public int CompanyID { get; set; }
        public int CustomerID { get; set; }
        public int ContractID { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Currency { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual COMPANy COMPANy { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual S_CONTRACTS S_CONTRACTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_ORDER_PRODUCTS> S_ORDER_PRODUCTS { get; set; }
    }
}
