//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPL
    {
        public int ID { get; set; }
        public int ProdID { get; set; }
        public string CarModel1 { get; set; }
        public string Option1 { get; set; }
        public Nullable<double> Option1UsageQty { get; set; }
        public string Option1UsageUnit { get; set; }
        public string CarModel2 { get; set; }
        public string Option2 { get; set; }
        public Nullable<double> Option2UsageQty { get; set; }
        public string Option2UsageUnit { get; set; }
        public string CarModel3 { get; set; }
        public string Option3 { get; set; }
        public Nullable<double> Option3UsageQty { get; set; }
        public string Option3UsageUnit { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
