//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAMPING_NORMS
    {
        public int ID { get; set; }
        public int PartID_before { get; set; }
        public int PartID_after { get; set; }
        public double Density { get; set; }
        public int QuantityOfStamps { get; set; }
        public double WeightOfStamps { get; set; }
        public double WeightOfWaste { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime IssuedDateTime { get; set; }
        public int IssuedByUserID { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual PART PART { get; set; }
        public virtual PART PART1 { get; set; }
    }
}
