//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STEEL_COILS
    {
        public int ID { get; set; }
        public string Marka { get; set; }
        public string Standart { get; set; }
        public string Coating { get; set; }
        public Nullable<double> Thickness { get; set; }
    }
}
