//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SUPPLIERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUPPLIERS()
        {
            this.P_CONTRACTS = new HashSet<P_CONTRACTS>();
            this.P_INVOICES = new HashSet<P_INVOICES>();
            this.P_ORDERS = new HashSet<P_ORDERS>();
        }
    
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        public string Address { get; set; }
        [Required]
        public string Country { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string ContactPersonName { get; set; }
        public string DirectorName { get; set; }
        public bool IsDeleted { get; set; }
        public string DUNS { get; set; }
        [Required]
        public string Type { get; set; }
        public string City { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_CONTRACTS> P_CONTRACTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_INVOICES> P_INVOICES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_ORDERS> P_ORDERS { get; set; }
    }
}
