//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACING
    {
        public int ID { get; set; }
        public int PackingListID { get; set; }
        public string ActualLocation { get; set; }
        public System.DateTime IssueDateTime { get; set; }
        public double ActualDistanceToDestination { get; set; }
        public System.DateTime ETA { get; set; }
        public string Comment { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual P_INVOICE_PACKINGLISTS P_INVOICE_PACKINGLISTS { get; set; }
    }
}
