//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ENTRIES
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string IP { get; set; }
        public string MAC { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
