//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tahsinERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WASTE_STOCKS
    {
        public int ID { get; set; }
        public int WHID { get; set; }
        public int WasteID { get; set; }
        public string Unit { get; set; }
        public double Amount { get; set; }
    
        public virtual PART_WRHS PART_WRHS { get; set; }
        public virtual WASTE WASTE { get; set; }
    }
}
